### ISSUE TITLE
[ci]: ESLint workflow fails when a pr is created from a fork

### ISSUE THREAD

**Issue by AnishDe12020** [AnishDe12020/devkit#19]
The error - 
![image](https://user-images.githubusercontent.com/63192115/143809824-27a67857-2bb0-4129-8c05-5eeb7384d9f2.png)

**Comment by krishguptadev** [comment]
Can I work on this?

**Comment by AnishDe12020** [comment]
> Can I work on this?

Yes

**Comment by nhcarrigan** [comment]
I'd try removing the third party action and updating your script to run your `lint` step.

**Comment by nhcarrigan** [comment]
Alternatively, if you're set on the action, you could run it on `pull_request_target` instead, though [this can be dangerous](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request_target).

**Comment by AnishDe12020** [comment]
> I'd try removing the third party action and updating your script to run your `lint` step.

That sounds good to me. @krishguptadev can you run `yarn lint` and `yarn prettier`?
