### ISSUE TITLE
New tool: HTML to JSX converter and vice versa

### ISSUE THREAD

**Issue by AnishDe12020** [AnishDe12020/devkit#26]
A tool that can convert given HTML code into JSX

**Comment by diganta413** [comment]
Can I try out this issue?

**Comment by AnishDe12020** [comment]
> Can I try out this issue?

Sure, I will assign it to you. Do reach out to me (by commenting on this issue) if you need any help

**Comment by diganta413** [comment]
Do you have any design of how the converter page will look like?

**Comment by AnishDe12020** [comment]
> Do you have any design of how the converter page will look like?

Nothing like a mock-up but I guess I can explain it in text. So mainly there is going to be an input (i have codemirror installed so that can be the code editor serving as the input) for HTML and hitting a convert button with give us the jsx in another read-only code editor

**Comment by diganta413** [comment]
Okk....

**Comment by diganta413** [comment]
@AnishDe12020 Html to jsx and Jsx to Html will be in same route or different?

**Comment by AnishDe12020** [comment]
> @AnishDe12020 Html to jsx and Jsx to Html will be in same route or different?

I am leaving this up to you. Do whatever is easier or whatever you feel is better. Just make sure they are under the same category (preferably the existing converters category)

**Comment by diganta413** [comment]
Ok...then I am making them separately...

**Comment by AnishDe12020** [comment]
> Hey @AnishDe12020 it seems that the library that is needed to convert html to jsx does not have any type declaration available....so where can I declare the types explicitly?

I think that should go into a folder called `@types`. In that you can make a file like `<library+name>.d.ts`

**Comment by diganta413** [comment]
Okk...so the @types folder should be in the root directory right?

**Comment by AnishDe12020** [comment]
> Okk...so the @types folder should be in the root directory right?

Yes
